apiVersion: v1
kind: Secret
metadata:
  name: platform-secrets
  labels:
    app.kubernetes.io/part-of: reusable-platform
type: Opaque
stringData:
  DB_PASSWORD: service_password
  POSTGRES_PASSWORD: service_password
  KC_DB_PASSWORD: keycloak
  KEYCLOAK_ADMIN: admin
  KEYCLOAK_ADMIN_PASSWORD: admin

